### PR TITLE
Add kube-burner and web-burner workflows

### PR DESCRIPTION
**Pull request by Harshith-umesh**
##Kube-burner workflows

Adding new Kube-burner workflows for node-density, node-density-heavy, node-density-cni, cluster-density and cluster-density v2 workloads.

Adding web-burner workflows for icni2 cluster-density2 and icni2 node-density2 workloads.

### CODE REVIEW

**Review by jaredoconnell — COMMENTED** [review]
Looks good, but I don't have a cluster to test this on.

**Review by dustinblack — CHANGES_REQUESTED** [review]
My one nit here is that I don't think it makes sense to copy the config.yaml into each workflow example directory. I think we should use the README to document the usage to the user, and there is already information there and a separate config file example for using podman, which will be the most likely local deployer for these end users.

**Comment by dustinblack** [comment]
We also might want to take the existing workflow and move it into something like an "everything" subdirectory to avoid any confusion with how it relates to the other single-job workflows.

**Comment by Harshith-umesh** [comment]
> We also might want to take the existing workflow and move it into something like an "everything" subdirectory to avoid any confusion with how it relates to the other single-job workflows.

yes will create a single subdirectory and move all of them there

**Comment by Harshith-umesh** [comment]
> My one nit here is that I don't think it makes sense to copy the config.yaml into each workflow example directory. I think we should use the README to document the usage to the user, and there is already information there and a separate config file example for using podman, which will be the most likely local deployer for these end users.

got it, yeah I was thinking the same thing!

**Comment by Harshith-umesh** [comment]
> > My one nit here is that I don't think it makes sense to copy the config.yaml into each workflow example directory. I think we should use the README to document the usage to the user, and there is already information there and a separate config file example for using podman, which will be the most likely local deployer for these end users.
> 
> got it, yeah I was thinking the same thing!

done

**Comment by Harshith-umesh** [comment]
> > We also might want to take the existing workflow and move it into something like an "everything" subdirectory to avoid any confusion with how it relates to the other single-job workflows.
> 
> yes will create a single subdirectory and move all of them there

done

**Review by dustinblack — APPROVED** [review]

**Pull request merged**
